-- Generated by tools/build_lua_data.py from tools/recipe_seed.json; do not edit by hand.
local MC = MaddinCrafts

MC:RegisterRecipes("WOODWORKING", {
    {
        id = "woodworking-simple-wooden-staff",
        name = "Simple Wooden Staff",
        profession = "WOODWORKING",
        requiredSkill = 1,
        sourceType = "ASCENSION_CUSTOM",
        sourceText = "Ascension/Bronzebeard woodworking starter recipe placeholder",
        recipeItemId = nil,
        teachesSpellId = nil,
        faction = "Neutral",
        reputation = nil,
        phase = "Ascension",
        verified = false,
        notes = "Ascension/Bronzebeard-only profession seed; retained to prove custom layering while IDs await source confirmation.",
    },
})
