-- Generated by tools/build_lua_data.py from tools/recipe_seed.json; do not edit by hand.
local MC = MaddinCrafts

MC:RegisterRecipes("WOODCUTTING", {
    {
        id = "woodcutting-rough-log",
        name = "Rough Log",
        profession = "WOODCUTTING",
        requiredSkill = 1,
        sourceType = "ASCENSION_CUSTOM",
        sourceText = "Ascension woodcutting starter recipe/source placeholder",
        recipeItemId = nil,
        teachesSpellId = nil,
        faction = "Neutral",
        reputation = nil,
        phase = "Ascension",
        verified = false,
        notes = "Ascension-only profession seed; exact spell and acquisition must be confirmed against Ascension DB/in-game.",
    },
})
