#!/usr/bin/env python3
"""Generate MaddinCrafts Lua recipe data from structured JSON.

The JSON seed keeps source URLs and curation metadata out of the runtime addon
while producing deterministic Lua files suitable for WoW 3.3.5 / Lua 5.1.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

RUNTIME_FIELDS = [
    "id",
    "name",
    "profession",
    "requiredSkill",
    "sourceType",
    "sourceText",
    "recipeItemId",
    "teachesSpellId",
    "faction",
    "reputation",
    "phase",
    "verified",
    "notes",
]

REQUIRED_FIELDS = [
    "id",
    "name",
    "profession",
    "requiredSkill",
    "sourceType",
    "sourceText",
    "phase",
    "verified",
]

PROFESSION_FILE_NAMES = {
    "ALCHEMY": "Alchemy.lua",
    "BLACKSMITHING": "Blacksmithing.lua",
    "COOKING": "Cooking.lua",
    "ENCHANTING": "Enchanting.lua",
    "ENGINEERING": "Engineering.lua",
    "FIRST_AID": "FirstAid.lua",
    "LEATHERWORKING": "Leatherworking.lua",
    "MINING": "Mining.lua",
    "TAILORING": "Tailoring.lua",
    "WOODCUTTING": "Woodcutting.lua",
    "WOODWORKING": "Woodworking.lua",
}

CUSTOM_SOURCE_PATTERN = re.compile(r"(^|[^A-Z0-9])(ASCENSION|COA|BRONZEBEARD)([^A-Z0-9]|$)")
GENERATED_HEADER = "-- Generated by tools/build_lua_data.py from tools/recipe_seed.json; do not edit by hand."

KNOWN_SOURCE_TYPES = {"ASCENSION_CUSTOM", "DROP", "QUEST", "SOURCE_PENDING", "TRAINER", "VENDOR"}
KNOWN_FACTIONS = {"Alliance", "Horde", "Neutral"}
KNOWN_PHASES = {"Ascension", "Classic", "WotLK"}


def lua_string(value: str) -> str:
    escaped = []
    for char in value:
        code = ord(char)
        if char == "\\":
            escaped.append("\\\\")
        elif char == '"':
            escaped.append('\\"')
        elif code < 32 or code == 127:
            escaped.append(f"\\{code:03d}")
        else:
            escaped.append(char)
    return f'"{"".join(escaped)}"'


def lua_value(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return lua_string(value)
    raise TypeError(f"unsupported Lua value type: {type(value).__name__}")


def recipe_label(recipe: dict, index: int) -> str:
    recipe_id = recipe.get("id")
    return str(recipe_id) if isinstance(recipe_id, str) and recipe_id else str(index)


def is_non_negative_int(value) -> bool:
    return type(value) is int and value >= 0


def validate_string_field(
    recipe: dict,
    index: int,
    field: str,
    errors: list[str],
    *,
    required: bool,
    nullable: bool = False,
) -> None:
    value = recipe.get(field)
    if value is None:
        if required:
            errors.append(f"recipe {recipe_label(recipe, index)} missing required field {field}")
        return
    if not isinstance(value, str):
        type_name = "str or null" if nullable else "str"
        errors.append(f"recipe {recipe_label(recipe, index)} field {field} must be {type_name}")
    elif required and value == "":
        errors.append(f"recipe {recipe_label(recipe, index)} missing required field {field}")


def validate_enum_field(recipe: dict, index: int, field: str, allowed: set[str], errors: list[str]) -> None:
    validate_string_field(recipe, index, field, errors, required=True)
    value = recipe.get(field)
    if isinstance(value, str) and value and value not in allowed:
        errors.append(f"recipe {recipe_label(recipe, index)} field {field} must be one of: {', '.join(sorted(allowed))}")


def validate_nullable_int_field(recipe: dict, index: int, field: str, errors: list[str]) -> None:
    value = recipe.get(field)
    if value is not None and not is_non_negative_int(value):
        errors.append(f"recipe {recipe_label(recipe, index)} field {field} must be a non-negative integer or null")


def validate_recipe(recipe: dict, index: int) -> list[str]:
    errors: list[str] = []
    for field in REQUIRED_FIELDS:
        if field not in recipe or recipe[field] in (None, ""):
            errors.append(f"recipe {recipe_label(recipe, index)} missing required field {field}")

    unknown_fields = sorted(set(recipe) - set(RUNTIME_FIELDS) - {"sourceUrls"})
    if unknown_fields:
        errors.append(f"recipe {recipe_label(recipe, index)} has unknown fields: {', '.join(unknown_fields)}")

    validate_string_field(recipe, index, "id", errors, required=True)
    validate_string_field(recipe, index, "name", errors, required=True)
    validate_string_field(recipe, index, "profession", errors, required=True)
    profession = recipe.get("profession")
    if isinstance(profession, str) and profession and profession not in PROFESSION_FILE_NAMES:
        errors.append(f"recipe {recipe_label(recipe, index)} unknown profession {profession}")
    validate_enum_field(recipe, index, "sourceType", KNOWN_SOURCE_TYPES, errors)
    validate_string_field(recipe, index, "sourceText", errors, required=True)
    validate_enum_field(recipe, index, "faction", KNOWN_FACTIONS, errors)
    validate_string_field(recipe, index, "reputation", errors, required=False, nullable=True)
    validate_enum_field(recipe, index, "phase", KNOWN_PHASES, errors)
    validate_string_field(recipe, index, "notes", errors, required=False)

    if not is_non_negative_int(recipe.get("requiredSkill")):
        errors.append(f"recipe {recipe_label(recipe, index)} field requiredSkill must be a non-negative integer")
    validate_nullable_int_field(recipe, index, "recipeItemId", errors)
    validate_nullable_int_field(recipe, index, "teachesSpellId", errors)

    if type(recipe.get("verified")) is not bool:
        errors.append(f"recipe {recipe_label(recipe, index)} field verified must be bool")

    source_urls = recipe.get("sourceUrls")
    if not isinstance(source_urls, list) or not source_urls or not all(isinstance(url, str) for url in source_urls):
        errors.append(f"recipe {recipe_label(recipe, index)} field sourceUrls must be a non-empty list of strings")
        source_urls = []

    source_text = f"{recipe.get('sourceType', '')} {recipe.get('sourceText', '')} {recipe.get('phase', '')}".upper()
    source_url_text = " ".join(source_urls).upper()
    is_custom_or_uncertain = bool(CUSTOM_SOURCE_PATTERN.search(source_text) or CUSTOM_SOURCE_PATTERN.search(source_url_text))
    if is_custom_or_uncertain and recipe.get("verified") is not False:
        errors.append(
            f"recipe {recipe_label(recipe, index)}: Ascension/CoA/Bronzebeard records must be verified=false until independently confirmed"
        )
    if is_custom_or_uncertain and not recipe.get("notes"):
        errors.append(f"recipe {recipe_label(recipe, index)}: uncertain records must include notes")

    return errors


def sort_key(recipe: dict):
    return (recipe["profession"], int(recipe["requiredSkill"]), recipe["name"].lower(), recipe["id"])


def render_profession(profession: str, recipes: list[dict]) -> str:
    lines = [
        GENERATED_HEADER,
        "local MC = MaddinCrafts",
        "",
        f"MC:RegisterRecipes({lua_string(profession)}, {{",
    ]
    for recipe in sorted(recipes, key=sort_key):
        lines.append("    {")
        for field in RUNTIME_FIELDS:
            lines.append(f"        {field} = {lua_value(recipe.get(field))},")
        lines.append("    },")
    lines.extend(["})", ""])
    return "\n".join(lines)


def load_seed(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get("recipes"), list):
        raise ValueError("seed JSON must be an object with a recipes array")
    return data["recipes"]


def remove_stale_generated_files(output_dir: Path) -> None:
    if not output_dir.exists():
        return
    for path in output_dir.glob("*.lua"):
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except IndexError:
            continue
        if first_line == GENERATED_HEADER:
            path.unlink()


def generate(input_path: Path, output_dir: Path) -> list[Path]:
    recipes = load_seed(input_path)
    errors: list[str] = []
    seen_ids: set[str] = set()
    seen_profession_spells: dict[tuple[str, int], str] = {}

    for index, recipe in enumerate(recipes, start=1):
        if not isinstance(recipe, dict):
            errors.append(f"recipe {index} is not an object")
            continue
        errors.extend(validate_recipe(recipe, index))
        recipe_id = recipe.get("id")
        if isinstance(recipe_id, str):
            if recipe_id in seen_ids:
                errors.append(f"recipe {recipe_label(recipe, index)} duplicate recipe id {recipe_id}")
            seen_ids.add(recipe_id)
        profession = recipe.get("profession")
        teaches_spell_id = recipe.get("teachesSpellId")
        if isinstance(profession, str) and type(teaches_spell_id) is int:
            key = (profession, teaches_spell_id)
            if key in seen_profession_spells:
                errors.append(
                    f"recipe {recipe_label(recipe, index)} duplicate profession/spell {profession}/{teaches_spell_id} already used by {seen_profession_spells[key]}"
                )
            else:
                seen_profession_spells[key] = recipe_label(recipe, index)

    if errors:
        raise ValueError("\n".join(errors))

    grouped: dict[str, list[dict]] = defaultdict(list)
    for recipe in recipes:
        grouped[recipe["profession"]].append(recipe)

    output_dir.mkdir(parents=True, exist_ok=True)
    remove_stale_generated_files(output_dir)
    written: list[Path] = []
    for profession in sorted(grouped):
        file_name = PROFESSION_FILE_NAMES[profession]
        path = output_dir / file_name
        path.write_text(render_profession(profession, grouped[profession]), encoding="utf-8")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="tools/recipe_seed.json", type=Path)
    parser.add_argument("--output-dir", default="data", type=Path)
    args = parser.parse_args(argv)

    try:
        written = generate(args.input, args.output_dir)
    except Exception as exc:  # noqa: BLE001 - CLI should print concise validation errors.
        print(str(exc), file=sys.stderr)
        return 1

    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
