#!/usr/bin/env python3
"""Generate MaddinCrafts Lua recipe data from structured JSON.

The JSON seed keeps source URLs and curation metadata out of the runtime addon
while producing deterministic Lua files suitable for WoW 3.3.5 / Lua 5.1.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

RUNTIME_FIELDS = [
    "id",
    "name",
    "profession",
    "requiredSkill",
    "sourceType",
    "sourceText",
    "recipeItemId",
    "teachesSpellId",
    "faction",
    "reputation",
    "phase",
    "verified",
    "notes",
]

REQUIRED_FIELDS = [
    "id",
    "name",
    "profession",
    "requiredSkill",
    "sourceType",
    "sourceText",
    "phase",
    "verified",
]

PROFESSION_FILE_NAMES = {
    "ALCHEMY": "Alchemy.lua",
    "BLACKSMITHING": "Blacksmithing.lua",
    "COOKING": "Cooking.lua",
    "ENCHANTING": "Enchanting.lua",
    "ENGINEERING": "Engineering.lua",
    "FIRST_AID": "FirstAid.lua",
    "LEATHERWORKING": "Leatherworking.lua",
    "TAILORING": "Tailoring.lua",
    "WOODCUTTING": "Woodcutting.lua",
    "WOODWORKING": "Woodworking.lua",
}

CUSTOM_SOURCE_PATTERN = re.compile(r"(^|[^A-Z0-9])(ASCENSION|COA|BRONZEBEARD)([^A-Z0-9]|$)")


def lua_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def lua_value(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return lua_string(value)
    raise TypeError(f"unsupported Lua value type: {type(value).__name__}")


def validate_recipe(recipe: dict, index: int) -> list[str]:
    errors: list[str] = []
    for field in REQUIRED_FIELDS:
        if field not in recipe or recipe[field] in (None, ""):
            errors.append(f"recipe {recipe.get('id', index)} missing required field {field}")

    if "sourceUrls" not in recipe or not recipe["sourceUrls"]:
        errors.append(f"recipe {recipe.get('id', index)} must include at least one source URL")

    unknown_fields = sorted(set(recipe) - set(RUNTIME_FIELDS) - {"sourceUrls"})
    if unknown_fields:
        errors.append(f"recipe {recipe.get('id', index)} has unknown fields: {', '.join(unknown_fields)}")

    source_text = f"{recipe.get('sourceType', '')} {recipe.get('sourceText', '')} {recipe.get('phase', '')}".upper()
    source_urls = " ".join(recipe.get("sourceUrls", [])).upper()
    is_custom_or_uncertain = bool(CUSTOM_SOURCE_PATTERN.search(source_text) or CUSTOM_SOURCE_PATTERN.search(source_urls))
    if is_custom_or_uncertain and recipe.get("verified") is not False:
        errors.append(
            f"recipe {recipe.get('id', index)}: Ascension/CoA/Bronzebeard records must be verified=false until independently confirmed"
        )
    if is_custom_or_uncertain and not recipe.get("notes"):
        errors.append(f"recipe {recipe.get('id', index)}: uncertain records must include notes")

    return errors


def sort_key(recipe: dict):
    return (recipe["profession"], int(recipe["requiredSkill"]), recipe["name"].lower(), recipe["id"])


def render_profession(profession: str, recipes: list[dict]) -> str:
    lines = [
        "-- Generated by tools/build_lua_data.py from tools/recipe_seed.json; do not edit by hand.",
        "local MC = MaddinCrafts",
        "",
        f"MC:RegisterRecipes({lua_string(profession)}, {{",
    ]
    for recipe in sorted(recipes, key=sort_key):
        lines.append("    {")
        for field in RUNTIME_FIELDS:
            lines.append(f"        {field} = {lua_value(recipe.get(field))},")
        lines.append("    },")
    lines.extend(["})", ""])
    return "\n".join(lines)


def load_seed(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get("recipes"), list):
        raise ValueError("seed JSON must be an object with a recipes array")
    return data["recipes"]


def generate(input_path: Path, output_dir: Path) -> list[Path]:
    recipes = load_seed(input_path)
    errors: list[str] = []
    grouped: dict[str, list[dict]] = defaultdict(list)

    for index, recipe in enumerate(recipes, start=1):
        if not isinstance(recipe, dict):
            errors.append(f"recipe {index} is not an object")
            continue
        errors.extend(validate_recipe(recipe, index))
        if "profession" in recipe:
            grouped[recipe["profession"]].append(recipe)

    if errors:
        raise ValueError("\n".join(errors))

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for profession in sorted(grouped):
        file_name = PROFESSION_FILE_NAMES.get(profession, profession.title().replace("_", "") + ".lua")
        path = output_dir / file_name
        path.write_text(render_profession(profession, grouped[profession]), encoding="utf-8")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="tools/recipe_seed.json", type=Path)
    parser.add_argument("--output-dir", default="data", type=Path)
    args = parser.parse_args(argv)

    try:
        written = generate(args.input, args.output_dir)
    except Exception as exc:  # noqa: BLE001 - CLI should print concise validation errors.
        print(str(exc), file=sys.stderr)
        return 1

    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
